---
- hosts: group1
  tasks:
     - name: installing tomcat
       yum: name=tomcat state=present
     - name: starting the service
       service: name=tomcat state=started
     - name: downloading the benefits.war
       get_url: 
          url: https://www.oracle.com/webfolder/technetwork/tutorials/obe/fmw/wls/12c/03-DeployApps/files/benefits.war
          dest: /usr/share/tomcat/webapps/benefits.war 
