---
- hosts: group1
  tasks:
  - name: downloading the splunk server
    get_url: url=https://www.splunk.com/bin/splunk/DownloadActivityServlet?architecture=x86_64&platform=linux&version=7.3.0&product=splunk&filename=splunk-7.3.0-657388c7a488-Linux-x86_64.tgz dest=/opt
  - name: unzipping the file
    command: tar -xvzf splunk-7.3.0-657388c7a488-Linux-x86_64.tgz -C /opt/ 
    command_warnings=False
#    unarchive: src=/opt/splunk-6.2.3-264376.i386.rpm dest=/opt remote_src=yes
#https://www.splunk.com/page/download_track?file=7.3.2/linux/splunk-7.3.2-c60db69f8e32-Linux-x86_64.tgz&platform
